# Site settings
author: Cody
title: Why I decided to become a software engineer
header-img: img/home-bg.png
email: codydupuis99@gmail.com
copyright_name: Cody
description: > # this means to ignore newlines until "baseurl:"
  Change of life course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CodyWD99

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
